### ISSUE TITLE
duplicate bucket creation with same name.

### ISSUE THREAD

**Issue by shalinikum** [0chain/minio#20]
>> Expected behaviour

## CreateBucket

This function will create a bucket for you and this bucket will be stored in 0chain allocation, it should be unique name

Example

```shell
curl -X GET -i 'http://localhost:3001/?action=createBucket&bucketName=${bucketname}'
```
Param:

* Action: "createBucket"
* bucketName: is the desired bucket name should be unique

Output:

```
{
  "Success": true,
  "Bucketname": "createdBucketName"
}
```
## Current Behavior
https://github.com/0chain/system_test/actions/runs/4713486509/jobs/8359216362?pr=634

[CreateBucket should return error when bucket name already exist] 
But right now I am able to create bucket with duplicate name.

my pr link : https://github.com/0chain/system_test/pull/634

**Comment by Jayashsatolia403** [comment]
This is not a bug and done on purpose.
