### ISSUE TITLE
Put object is giving Internal error

### ISSUE THREAD

**Issue by shalinikum** [0chain/minio#21]
https://dev-3.devnet-0chain.net/zs3server returned {"error":"We encountered an internal error, please try again."} with status 500 Internal Server Error
 test link : https://github.com/0chain/system_test/actions/runs/4713486509/jobs/8359216362?pr=634
pr link : https://github.com/0chain/system_test/pull/634

## putObject

This function is to upload object to zs3server 

Example:

```shell 
curl -X GET -F 'file=@path-to-file' http://localhost:3001/?action=putObject\&accessKey=rootroot\&secretAccessKey=rootroot\&bucketName=test2

```

Param:

* ``action`` : "putObject"
* ``bucketName``: the bucket name that you want to list its objects

Form:

* this API require a form filed with name ``file`` so it can upload this file to zs3server 

## Current Behavior
PutObjects should return 200 all the parameter are correct] start at [04-16-2023 15:27:55] 
    zs3_client.go:76: https://dev-3.devnet-0chain.net/zs3server returned {"error":"We encountered an internal error, please try again."} with status 500 Internal Server Error
    assertions.go:264: 
        	Error Trace:	/root/actions-runner3/_work/system_test/system_test/tests/api_tests/zs3server_opertions_test.go:70
        	            				/root/actions-runner3/_work/system_test/system_test/tests/api_tests/system_test_framework.go:86
        	            				/root/actions-runner3/_work/system_test/system_test/tests/api_tests/asm_amd64.s:1571
        	Error:      	Not equal: 
        	            	expected: 200
        	            	actual  : 500
        	Test:       	TestZs3ServerOpertions/PutObjects_should_return_200_all_the_parameter_are_correct
    zs3server_opertions_test.go:58: Test case [PutObjects should return 200 all the parameter are correct] exit at

**Comment by dabasov** [comment]
could not reproduce, please check with binary files and reopen in case of an error
