### ISSUE TITLE
[RemoveObject should return error if object doen't exist]

### ISSUE THREAD

**Issue by shalinikum** [0chain/minio#22]
Error Trace:	/root/actions-runner3/_work/system_test/system_test/tests/api_tests/zs3server_opertions_test.go:133
        	            				/root/actions-runner3/_work/system_test/system_test/tests/api_tests/system_test_framework.go:86
        	            				/root/actions-runner3/_work/system_test/system_test/tests/api_tests/asm_amd64.s:1571
        	Error:      	Not equal: 
        	            	expected: 500
        	            	actual  : 200
        	Test:       	TestZs3ServerOpertions/RemoveObject_should_return_error_if_object_doen't_exist
        	
        I am getting 200 okay for this but Ideally I should get some error.
        
        Test run link: https://github.com/0chain/system_test/actions/runs/4713486509/jobs/8359216362?pr=634
pr link : https://github.com/0chain/system_test/pull/634

**Comment by Jayashsatolia403** [comment]
This is not a bug and done on purpose.
