### ISSUE TITLE
Files not uploading via multiupload when destination is a nested bucket location

### ISSUE THREAD

**Issue by sunilmhta** [0chain/minio#61]
When we upload files from `mc` using the new multiupload endpoint, and the destination bucket is a nested bucket location like: `buck1/nested1`, the file which is being copied does not appear inside the bucket.

## Expected Behavior
Without multiupload when I try to upload a file named `staticcheck.conf` inside the bucket `buck1/nest1` the files appear in the `buck1` bucket like this:
<img width="1181" alt="image" src="https://github.com/0chain/zs3server/assets/15699710/c9fea19f-f5cd-42cc-b708-fef1798525a8">

## Current Behavior
Currently the file being copied does not appear. 
<img width="1179" alt="image" src="https://github.com/0chain/zs3server/assets/15699710/887425a5-9dda-4881-a82c-3d604b02c12b">

**Comment by boddumanohar** [comment]
fixed by: https://github.com/0chain/zs3server/pull/63
